version: "3.4"

x-base-image: &base-image
  network_mode: none
  volumes:
    - ${PWD}:/home
  working_dir: /home

services:
  lint:
    <<: *base-image
    build:
      context: .
      dockerfile: ./images/Dockerfile.lint
